#!/usr/bin/env python3
"""
NAME
       confsnap - a tool for highlighting system changes

SYNOPSIS
       confsnap

DESCRIPTION
       confsnap is a small (maybe growing set of) snapshots that make it
       easier to tell when things have changed on a system.

       Currently supported:

       - Currently installed RPMs

       Data is signed and stored under /var/lib/confsnap/snapshots/
"""
import os
import subprocess
import sys
import time
import logging


logging.basicConfig(
    format="%(asctime)s %(levelname)s %(message)s",
    level=logging.INFO,
)

SNAPSHOTS_DIR = os.environ.get("CONFSNAP_SNAPSHOTS_DIR", "/var/lib/confsnap/snapshots")
logger = logging.getLogger(__name__)


def ts():
    return int(time.time())


def fexists(path):
    return os.path.isfile(path)


def dexists(path):
    return os.path.isdir(path)


def snap_rpms(snapshot_dir):
    rpm_snapshot_path = os.path.join(snapshot_dir, "rpms.txt")
    logger.debug("saving RPM snapshot")

    try:
        with open(rpm_snapshot_path, "wb") as rpm_snapshot_file:
            subprocess.run(
                ["rpm", "-q", "-a"],
                stdout=rpm_snapshot_file,
            )
    except Exception as e:
        if fexists(rpm_snapshot_path):
            os.unlink(rpm_snapshot_path)
        raise e

    logger.info("saved RPM snapshot")


def main(argv):
    os.umask(0o0277)
    snapshot_dir = os.path.join(SNAPSHOTS_DIR, str(ts()))
    logger.debug('saving snapshot dir: snapshot_dir="%s"', snapshot_dir)
    os.makedirs(snapshot_dir, mode=0o750)
    logger.info('created snapshot dir: snapshot_dir="%s"', snapshot_dir)
    snap_rpms(snapshot_dir)


if __name__ == "__main__":
    main(sys.argv)
